[package]
name = "pm"
version = "0.1.0"
authors = ["pgl888999@icloud.com"]
license = "MIT OR Apache-2.0"
description = "A tool to manage this project"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }