name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aiohappyeyeballs=2.4.0=py312hca03da5_0
  - aiohttp=3.10.5=py312h80987f9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - anaconda-anon-usage=0.4.4=py312hd6b623d_100
  - anaconda-catalogs=0.2.0=py312hca03da5_1
  - anaconda-client=1.12.3=py312hca03da5_0
  - anaconda-project=0.11.1=py312hca03da5_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - attrs=23.1.0=py312hca03da5_0
  - beautifulsoup4=4.12.3=py312hca03da5_0
  - boltons=23.0.0=py312hca03da5_0
  - boost-cpp=1.82.0=h48ca7d4_2
  - brotli-python=1.0.9=py312h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - cctools=949.0.1=hc179dcd_25
  - cctools_osx-arm64=949.0.1=h332cad3_25
  - certifi=2026.01.04=py312hca03da5_0
  - cffi=1.17.1=py312h3eb5a62_0
  - chardet=4.0.0=py312hca03da5_1003
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py312hca03da5_0
  - conda=24.11.3=py312hca03da5_0
  - conda-build=24.9.0=py312hca03da5_0
  - conda-content-trust=0.2.0=py312hca03da5_1
  - conda-index=0.5.0=py312hca03da5_0
  - conda-libmamba-solver=24.9.0=pyhd3eb1b0_0
  - conda-pack=0.7.1=py312hca03da5_0
  - conda-package-handling=2.3.0=py312hca03da5_0
  - conda-package-streaming=0.10.0=py312hca03da5_0
  - conda-token=0.5.0=pyhd3eb1b0_0
  - cryptography=43.0.0=py312hd4332d6_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py312hca03da5_0
  - expat=2.6.3=h313beb8_0
  - filelock=3.13.1=py312hca03da5_0
  - fmt=9.1.0=h48ca7d4_1
  - fontconfig=2.14.2=h82840c6_0
  - freetype=2.13.3=h47d26ad_0
  - frozendict=2.4.2=py312hca03da5_0
  - frozenlist=1.4.0=py312h80987f9_0
  - fsspec=2024.6.1=py312hca03da5_0
  - gettext=0.21.0=hbdbcc25_2
  - icu=73.1=h313beb8_0
  - idna=3.7=py312hca03da5_0
  - intake=2.0.7=py312hca03da5_0
  - jinja2=3.1.4=py312hca03da5_0
  - jpeg=9e=h80987f9_3
  - jsonpatch=1.33=py312hca03da5_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jsonschema=4.23.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter_core=5.7.2=py312hca03da5_0
  - lcms2=2.17=h7418793_0
  - ld64=530=hb29bf3f_25
  - ld64_osx-arm64=530=h001ce53_25
  - ldid=2.1.5=h20b2a84_3
  - lerc=4.0.0=hd64df32_1
  - libarchive=3.7.4=h8f13d7a_0
  - libboost=1.82.0=h0bc93f9_2
  - libcurl=8.16.0=h01d3526_0
  - libcxx=21.1.8=hf598326_0
  - libdeflate=1.22=hd74edd7_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.6.3=hf9b8971_0
  - libffi=3.4.4=hca03da5_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libidn2=2.3.3=he4db4b2_0
  - liblief=0.12.3=h313beb8_0
  - libllvm14=14.0.6=h19fdd8a_4
  - liblzma=5.8.1=h39f12f2_2
  - liblzma-devel=5.8.1=h39f12f2_2
  - libmamba=1.5.8=haeffa04_3
  - libmambapy=1.5.8=py312h1c5506f_3
  - libnghttp2=1.57.0=h62f6fdd_0
  - libpng=1.6.39=h80987f9_0
  - libsolv=0.7.29=h1efcc80_0
  - libsqlite=3.46.0=hfb93653_0
  - libssh2=1.11.1=h3e2b118_0
  - libtiff=4.7.1=h367c460_0
  - libunistring=0.9.10=h3422bc3_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.13.1=h0b34f26_2
  - libzlib=1.2.13=hfb2fe0b_6
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py312h80987f9_0
  - menuinst=2.1.2=py312hca03da5_0
  - more-itertools=10.3.0=py312hca03da5_0
  - multidict=6.0.4=py312h80987f9_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - networkx=3.3=py312hca03da5_0
  - nspr=4.38=heaf21c2_0
  - nss=3.100=hc6e9f88_0
  - openjpeg=2.5.2=h54b8e55_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=24.1=py312hca03da5_0
  - patch=2.7.6=h1a28f6b_1001
  - pcre2=10.46=h1dacb4a_0
  - pip=24.2=py312hca03da5_0
  - pixman=0.46.4=h81086ad_1
  - pkginfo=1.10.0=py312hca03da5_0
  - platformdirs=3.10.0=py312hca03da5_0
  - pluggy=1.0.0=py312hca03da5_1
  - poppler=24.09.0=hba2596d_3
  - poppler-data=0.4.12=hd8ed1ab_0
  - psutil=5.9.0=py312h80987f9_0
  - py-lief=0.12.3=py312h313beb8_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h80987f9_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.2=hdf0ec26_0_cpython
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.16.2=py312hca03da5_0
  - python-libarchive-c=5.1=pyhd3eb1b0_0
  - python.app=3=py312h80987f9_1
  - python_abi=3.12=8_cp312
  - pytz=2024.1=py312hca03da5_0
  - pyyaml=6.0.1=py312h80987f9_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - reproc=14.2.4=h313beb8_2
  - reproc-cpp=14.2.4=h313beb8_2
  - requests=2.32.3=py312hca03da5_0
  - requests-toolbelt=1.0.0=py312hca03da5_0
  - rpds-py=0.10.6=py312hf0e4da2_0
  - ruamel.yaml=0.18.6=py312h80987f9_0
  - ruamel.yaml.clib=0.2.8=py312h80987f9_0
  - ruamel_yaml=0.17.21=py312h80987f9_0
  - setuptools=75.1.0=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py312hca03da5_0
  - tapi=1100.0.11=h8754e6a_1
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.1=py312h80987f9_0
  - tqdm=4.66.5=py312h989b03a_0
  - traitlets=5.14.3=py312hca03da5_0
  - truststore=0.8.0=py312hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - urllib3=2.2.3=py312hca03da5_0
  - wcwidth=0.2.14=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - xz=5.8.1=h9a6d368_2
  - xz-gpl-tools=5.8.1=h9a6d368_2
  - xz-tools=5.8.1=h39f12f2_2
  - yaml=0.2.5=h1a28f6b_0
  - yaml-cpp=0.8.0=h313beb8_1
  - yarl=1.11.0=py312h80987f9_0
  - zlib=1.2.13=hfb2fe0b_6
  - zstandard=0.23.0=py312h1a4646a_0
  - zstd=1.5.6=hfb09047_0
prefix: /opt/anaconda3
